export const NETWORK_ERROR = 'NETWORK_ERROR';
export const UN_AUTHOTIZED_ACCESS = 'UN_AUTHOTIZED_ACCESS';
export const REALIZATIOn_NOT_ALLOWED = 'REALIZATIOn_NOT_ALLOWED';
export const FAILED_SMS_VALIDATION = 'FAILED_SMS_VALIDATION';
export const PASSOWRD_VALIDATION_FAILED = 'PASSOWRD_VALIDATION_FAILED';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';