
FROM ubuntu:latest

RUN apt-get update && apt-get install -y \
  curl \
  python-software-properties
RUN curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
RUN apt-get install -y nodejs git \
  libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++
