export const APPROVE_GROUP_INVATATION = 'approve_invite';
export const ASK_GROUP_INVATATION = 'ask_invite';
export const ADD_FOLLOW_PROMOTION ='ADD_GROUP_FOLLOW_ON_ACTION';
export const ADD_BUSINESS_FOLLOW_ON_ACTION ='ADD_BUSINESS_FOLLOW_ON_ACTION';
export const GENERAL_NOTIFICATION = "NONE";
