export const GROUP_FETCH_REQUESTED = 'GROUP_FETCH_REQUESTED';
export const BUSINESS_FETCH_REQUESTED = 'BUSINESS_FETCH_REQUESTED';
export const FEED_MAIN_FETCH_REQUESTED = 'FEED_MAIN_FETCH_REQUESTED';
export const GROUP_FEED_FETCH_TOP_REQUESTED = 'GROUP_FEED_FETCH_TOP_REQUESTED';
export const NOTIFICATION_FETCH_REQUESTED = 'NOTIFICATION_FETCH_REQUESTED';
export const BUSINESS_PROMOTION_FETCH_REQUESTED = 'BUSINESS_PROMOTION_FETCH_REQUESTED';
