
export const SAVE_USER_REQUEST = 'SAVE_USER_REQUEST';
export const UPDATE_BUSINESS_REQUEST = 'UPDATE_BUSINESS_REQUEST';
export const UPDATE_BUSINESS_CATEGORY_REQUEST = 'UPDATE_BUSINESS_CATEGORY_REQUEST';
export const UPDATE_BUSINESS_REQUEST_FIRST_TIME = 'UPDATE_BUSINESS_REQUEST_FIRST_TIME';

//Feed
export const FEED_SCROLL_DOWN = 'FEED_SCROLL_DOWN';
export const FEED_SCROLL_UP = 'FEED_SCROLL_UP';

//notifications
export const SAVE_NOTIFICATION_REQUEST = 'SAVE_NOTIFICATION_REQUEST';

//my promotions
export const SAVE_MYPROMOTIONS_REQUEST = 'SAVE_MYPROMOTIONS_REQUEST';



