# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'THIS' do


   use_frameworks!

  pod 'Firebase/Core'
  pod 'FirebaseMessaging'
  pod 'Fabric', '~> 1.7.5'
  pod 'Crashlytics', '~> 3.10.1'
  pod 'react-native-config', :path => '../node_modules/react-native-config'

  pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'

end

