
export const SAVE_USER_REQUEST = 'SAVE_USER_REQUEST';
export const UPDATE_BUSINESS_REQUEST = 'UPDATE_BUSINESS_REQUEST';
export const UPDATE_BUSINESS_PROMOTIONS = 'UPDATE_BUSINESS_PROMOTIONS';
export const UPDATE_BUSINESS_PRODUCTS = 'UPDATE_BUSINESS_PRODUCTS';
export const UPDATE_BUSINESS_PERMISSIONS = 'UPDATE_BUSINESS_PERMISSIONS';
export const SAVE_BUSINESS = 'SAVE_BUSINESS';
export const UPDATE_BUSINESS = 'UPDATE_BUSINESS';
export const UPDATE_BUSINESS_CATEGORY_REQUEST = 'UPDATE_BUSINESS_CATEGORY_REQUEST';
export const UPDATE_BUSINESS_REQUEST_FIRST_TIME = 'UPDATE_BUSINESS_REQUEST_FIRST_TIME';

//Feed
export const FEED_SCROLL_DOWN = 'FEED_SCROLL_DOWN';
export const FEED_SET_SOCIAL_STATE = 'FEED_SET_SOCIAL_STATE';
export const FEED_SET_TOP_FEED = 'FEED_SET_TOP_FEED';
export const FEED_UPDATE_ITEM = 'FEED_UPDATE_ITEM';
export const FEED_UPDATE_SAVED_ITEM = 'FEED_UPDATE_SAVED_ITEM';
export const FEED_SCROLL_UP = 'FEED_SCROLL_UP';
export const LISTEN_FOR_MAIN_FEED= 'LISTEN_FOR_MAIN_FEED';
export const CANCEL_MAIN_FEED_LISTENER= 'CANCEL_MAIN_FEED_LISTENER';

//notifications
export const SAVE_NOTIFICATION_REQUEST = 'SAVE_NOTIFICATION_REQUEST';
export const SAVE_NOTIFICATION_TOP_REQUEST = 'SAVE_NOTIFICATION_TOP_REQUEST';
export const ADD_COMMENT_NOTIFICATION = "ADD_COMMENT_NOTIFICATION";
export const ADD_GENERAL_NOTIFICATION = "ADD_GENERAL_NOTIFICATION";

//my promotions
export const SAVE_MYPROMOTIONS_REQUEST = 'SAVE_MYPROMOTIONS_REQUEST';
export const SAVE_SINGLE_MYPROMOTIONS_REQUEST = 'SAVE_SINGLE_MYPROMOTIONS_REQUEST';
export const UPDATE_SINGLE_MYPROMOTIONS_REQUEST = 'UPDATE_SINGLE_MYPROMOTIONS_REQUEST';

//groups
export const SAVE_GROUPS_REQUEST = 'SAVE_GROUPS_REQUEST';
export const UPDATE_GROUPS_REQUEST = 'UPDATE_GROUPS_REQUEST';
export const SAVE_GROUP = 'SAVE_GROUP';
export const GROUP_CHAT_SCROLL_UP= 'GROUP_CHAT_SCROLL_UP';
export const GROUP_SYNC_CHAT= 'GROUP_SYNC_CHAT';
export const LISTEN_FOR_GROUP_FEED= 'LISTEN_FOR_GROUP_FEED';
export const CANCEL_GROUP_FEED_LISTENER= 'CANCEL_MAIN_FEED_LISTENER';
export const GROUP_FEED_SET_TOP_FEED = 'GROUP_FEED_SET_TOP_FEED';
export const GROUP_FEED_SCROLL_DOWN = 'GROUP_FEED_SCROLL_DOWN';
export const UPDATE_GROUPS_FOLLOWERS = 'UPDATE_GROUPS_FOLLOWERS';
export const GET_NEXT_GROUPS_FOLLOWERS = 'GET_NEXT_GROUPS_FOLLOWERS';
// groups

export const LISTEN_FOR_GROUP_CHATS= 'LISTEN_FOR_GROUP_CHATS';
export const CANCEL_GROUP_CHAT_LISTENER = 'CANCEL_GROUP_CHAT_LISTENER';


// group instance
export const GROUP_INSTANCE_CHAT_SCROLL_UP = 'GROUP_INSTANCE_CHAT_SCROLL_UP';
export const LISTEN_FOR_GROUP_INSTANCE_CHATS= 'LISTEN_FOR_GROUP_INSTANCE_CHATS';
export const CANCEL_GROUP_INSTANCE_CHAT_LISTENER = 'CANCEL_GROUP_INSTANCE_CHAT_LISTENER';


//promotion
export const SAVE_PROMOTION = 'SAVE_PROMOTION';
export const UPDATE_PROMOTION = 'UPDATE_PROMOTION';
export const PROMOTION_NOTIFICATION = 'PROMOTION_NOTIFICATION';


//product
export const SAVE_PRODUCT = 'SAVE_PRODUCT';
//post
export const SAVE_POST = 'SAVE_POST';

//feed comments

export const FEED_CHAT_SCROLL_UP = 'FEED_CHAT_SCROLL_UP';
export const FEED_SYNC_CHAT = 'FEED_SYNC_CHAT';
// change tav
export const CHANGE_TAB = 'CHANGE_TAB';